name: test

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go: ['1.17', '1.18', '1.19', '1.20', '1.21']

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go}}

      - name: build
        run: go build
